name: 🛠 Android CI / Build & Release APK

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # allow creating/updating Releases & uploading assets
  actions:  read    # allow pulling marketplace actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3
      
      - name: 🚀 Cache pub deps
        uses: actions/cache@v3
        with:
          path: ~/front-end/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ☕️ Setup Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3

      - name: 📥 Get dependencies
        run: |
          cd front-end
          flutter pub get

      # - name: ✅ Run tests
      #   run: |
      #     cd front-end
      #     flutter test --coverage

      - name: 🏗️ Build APKs
        run: |
          cd front-end
          flutter build apk --release --split-per-abi

      - name: 📦 Prepare artifacts
        run: |
          cd front-end
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/*.apk artifacts/

      # ─────────────── ONLY ON TAGS ───────────────
      - name: 🏷️ Create or update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: front-end/artifacts/*.apk
          token:     ${{ secrets.ACTION_TOKEN }}
